### PR TITLE
Small document updates

### PR DESCRIPTION
**Pull request by trsqr**
With [ESP32-DevKitC V4](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html)  no need for logic converters.

My unit doesn't have horizontal swing, commented out those.

### CODE REVIEW

**Comment by DomiStyle** [comment]
Thanks, but I would rather not add the note about the ESP32-DevKitC V4 as is.

There is no special circuit in that PCB to make it more 5V tolerant than other ESP32 boards, it just has a 5V power supply like many others. While all ESP32s are 5V tolerant to some degree it is out of spec according to Espressif.

If the current is not too high it will most likely work just fine but might degrade the hardware over time.

You could add a general note about this topic though, maybe something like this:

Note: It is possible to connect most ESP32 and ESP8266 boards directly to the AC but be advised that doing so will operate the chip out of spec.

**Comment by trsqr** [comment]
I don't claim to be an expert, but I thought there's an AMS1117 voltage regulator to make sure that the ESP32 gets 3.3 volts:

image

**Comment by DomiStyle** [comment]
That's only the power supply. The GPIO pins are connected directly to the ESP.

**Comment by trsqr** [comment]
Ah, now I understood - the question is about the digital inputs and not about the power supply (and there seems to be conflicting information about their 5V safeness over the internet). Apologies, let's close this PR.

**Pull request closed without merging**
