### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trsqr**
Add note that regarding usage of CN-CNT and CN-WLAN.

### CODE REVIEW

**Comment by trsqr** [comment]
No, sorry. I haven't built my unit yet even. Will do so though! I'm bit
tempted to order IgorYbema's ready built HeishaMon device though and flash
it with esphome-panasonic-ac. I think you came to the conclusion that it
should work?

**Comment by jkaberg** [comment]
@trsqr Very interesting, did you around to this?

**Comment by orosam** [comment]
Hi! 
I did test it, it does work indeed. 
I have a CS-Z25VKEW, it has the original DNSK-P11 installed on CN-WLAN and the ESP on CN-CNT. The unit can be controlled both via HA and the Panasonic app, simultaneously.

**Comment by DomiStyle** [comment]
Thanks for confirming!

**Pull request merged**
