### PR TITLE
Implement ECONAVI mode/preset

### PR DESCRIPTION
**Pull request by blacklizard**
Hi

I tried to implement ECONAVI functionality that is available in my AC. 
https://www.panasonic.com/my/consumer/air-solutions/air-conditioner/cs-s13tkh.html

Please verify if what I did is acceptable.

### CODE REVIEW

**Comment by DomiStyle** [comment]
Can you check if you can enable econavi and powerful/quiet at the same time via the IR remote?

**Comment by blacklizard** [comment]
@DomiStyle  No. If ECONAVI is enabled, it will disable quite mode, if quite mode is enabled, it will disable ECONAVI.

**Comment by DomiStyle** [comment]
I moved the econavi option from the presets to a switch like nanoeX since it's not supported by every AC.

Can you give it a try? Just add the switch to your config:

```
climate:
  - platform: panasonic_ac
    econavi_switch:
      name: Econavi switch
```

I'm not overwriting the state when switching from normal to powerful yet, maybe you can check how the AC handles it.

**Comment by blacklizard** [comment]
@DomiStyle I have tested your changes, the switch is working as intended.
I dont have powerful/turbo mode.  I only have Quite mode, so when ECONAVI is enabled, if i trun on Quite mode/preset, it behave correctly which is to turn off ECONAVI

**Comment by DomiStyle** [comment]
Thanks, for testing. Added the switch to the documentation and merged the pull request.

**Comment by blacklizard** [comment]
@DomiStyle Thanks.. Im still trying to figure out nanoe-G location, current pooling result does not return the state of nanoe-G. I've place an order for CZ-TACG1 and logic analyser, will try to figure out how nanoe-G is set.

**Pull request merged**
