### PR TITLE
Rework code for external_components

### LINKED ISSUE #16: ESPHome external Components
This is great and I hope someday that you decide to get this merged into ESPHome directly. Until then it would be great if you could structure the code as a standard component so that people can use it with [external_components](https://esphome.io/components/external_components.html)

This would allow people to update a lot easier as that is handled by ESPHome itself.

### PR DESCRIPTION
**Pull request by jesserockz**
I got bored and decided to do this...haha

Because I pretty much moves the files, and reformatted them, and changed quite a lot, its hard to get a real diff.

But this code is working for my CN-CNT based AC. 

I have updated the yaml example with how to use it. (The repo/branch in yaml will need to be updated if you decide to merge this in)

Closes #16

### CODE REVIEW

**Comment by DomiStyle** [comment]
Hurrah for programmers being bored. Will try this out on both of my units soon.

**Comment by DomiStyle** [comment]
I tested both modules and everything looks good to me except some minor issues that I can fix later.

Thanks, that looked like a lot of work!

**Comment by jesserockz** [comment]
Yeah I couldn't test everything and didn't want to alter the code too much unnecessarily.
Had lots on my mind while doing it though where changes could be made (should have made notes) haha

**Comment by DomiStyle** [comment]
@jesserockz Feel free to add any changes you want if you are bored again. My C++ skills are subpar at best.

Once the new ESPHome version comes out everything should be ready for master branch finally.

**Pull request merged**
